/*
TA_GEOTECH_FICHIER : Création de la table TA_GEOTECH_FICHIER regroupant tous les sites géotechniques.
*/

-- 1. La table
CREATE TABLE G_GEO.TA_GEOTECH_FICHIER (
	"OBJECTID" NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"FICHIER" VARCHAR2(4000),
    "FID_ETUDE" NUMBER(38,0)
 );

-- 2. Les commentaires
COMMENT ON TABLE G_GEO.TA_GEOTECH_FICHIER IS 'Table permettant de lister tous les fichiers correspondant à une étude (dwg, pdf, etc).';
COMMENT ON COLUMN G_GEO.TA_GEOTECH_FICHIER.OBJECTID IS 'Clé primaire auto-incrémentée de la table.';
COMMENT ON COLUMN G_GEO.TA_GEOTECH_FICHIER.FICHIER IS 'Nom du fichier.';
COMMENT ON COLUMN G_GEO.TA_GEOTECH_FICHIER.FID_ETUDE IS 'Clé étrangère vers la table TA_GEOTECH_ETUDE permettant d''associer une étude à un ou plusieurs fichiers.';

-- 3. Les contraintes
-- Contrainte de clé primaire
ALTER TABLE G_GEO.TA_GEOTECH_FICHIER
ADD CONSTRAINT TA_GEOTECH_FICHIER_PK
PRIMARY KEY("OBJECTID")
USING INDEX TABLESPACE G_ADT_INDX;

-- 4. Les index
CREATE INDEX TA_GEOTECH_FICHIER_FID_ETUDE_FICHIER_IDX ON G_GEO.TA_GEOTECH_FICHIER("FID_ETUDE", "FICHIER")
    TABLESPACE G_ADT_INDX;

-- 5. Les droits de lecture, écriture, suppression
GRANT SELECT ON G_GEO.TA_GEOTECH_FICHIER TO G_ADMIN_SIG;

/

