/*
TA_GEOTECH_BUREAU_ETUDE : Création de la table TA_GEOTECH_BUREAU_ETUDE permettant de lier chaque étude à un ou plusieurs bureaux d''étude.
*/

-- 1. La table
CREATE TABLE G_GEO.TA_GEOTECH_BUREAU_ETUDE (
	"OBJECTID" NUMBER(38,0) DEFAULT G_GEO.SEQ_TA_GEOTECH_BUREAU_ETUDE_OBJECTID.NEXTVAL NOT NULL,
	"NOM" VARCHAR2(300),
	"FID_ETUDE" NUMBER(38,0)
 );

-- 2. Les commentaires
COMMENT ON TABLE G_GEO.TA_GEOTECH_BUREAU_ETUDE IS 'Table permettant de lier chaque étude à un ou plusieurs bureaux d''étude.';
COMMENT ON COLUMN G_GEO.TA_GEOTECH_BUREAU_ETUDE.OBJECTID IS 'Clé primaire auto-incrémentée de la table.';
COMMENT ON COLUMN G_GEO.TA_GEOTECH_BUREAU_ETUDE.NOM IS 'Nom du bureau d''étude.';
COMMENT ON COLUMN G_GEO.TA_GEOTECH_BUREAU_ETUDE.FID_ETUDE IS 'Clé étrangère vers la table TA_GEOTECH_ETUDE permettant d''associer une étude à un ou plusieurs bureaux d''étude.';

-- 3. Les contraintes
-- Contrainte de clé primaire
ALTER TABLE G_GEO.TA_GEOTECH_BUREAU_ETUDE
ADD CONSTRAINT TA_GEOTECH_BUREAU_ETUDE_PK
PRIMARY KEY("OBJECTID")
USING INDEX TABLESPACE G_ADT_INDX;

-- Contrainte de clé étrangère
ALTER TABLE G_GEO.TA_GEOTECH_BUREAU_ETUDE
ADD CONSTRAINT TA_GEOTECH_BUREAU_ETUDE_FID_ETUDE_FK
FOREIGN KEY("FID_ETUDE")
REFERENCES G_GEO.TA_GEOTECH_ETUDE("OBJECTID");

-- 4. Les index
CREATE INDEX TA_GEOTECH_BUREAU_ETUDE_NOM_IDX ON G_GEO.TA_GEOTECH_BUREAU_ETUDE("NOM")
    TABLESPACE G_ADT_INDX;

CREATE INDEX TA_GEOTECH_BUREAU_ETUDE_FID_TYPE_ETUDE_IDX ON G_GEO.TA_GEOTECH_BUREAU_ETUDE("FID_TYPE_ETUDE")
    TABLESPACE G_ADT_INDX;

-- 5. Les droits de lecture, écriture, suppression
GRANT SELECT ON G_GEO.TA_GEOTECH_BUREAU_ETUDE TO G_ADMIN_SIG;

/

