/*
TA_GEOTECH_LIBELLE_LONG : Création de la table TA_GEOTECH_LIBELLE_LONG qui contient les libellés des objets liées aux études géotechniques.
*/

-- 1. La table
CREATE TABLE G_GEO.TA_GEOTECH_LIBELLE_LONG (
	"OBJECTID" NUMBER(38,0) DEFAULT G_GEO.SEQ_TA_GEOTECH_LIBELLE_LONG_OBJECTID.NEXTVAL NOT NULL,
	"VALEUR" VARCHAR2(300 BYTE)
 );

-- 2. Les commentaires
 COMMENT ON TABLE G_GEO.TA_GEOTECH_LIBELLE_LONG IS 'Table regroupant les libellés long qualifiant les objets de la base G_GEOTECH.';
COMMENT ON COLUMN G_GEO.TA_GEOTECH_LIBELLE_LONG.OBJECTID IS 'Identifiant de chaque famille de libellés.';
COMMENT ON COLUMN G_GEO.TA_GEOTECH_LIBELLE_LONG.VALEUR IS 'Valeur décrivant les types d''objets répartis par famille.';

-- 3. Les contraintes
-- Contrainte de clé primaire
ALTER TABLE G_GEO.TA_GEOTECH_LIBELLE_LONG
ADD CONSTRAINT TA_GEOTECH_LIBELLE_LONG_PK
PRIMARY KEY("OBJECTID")
USING INDEX TABLESPACE G_ADT_INDX;

-- Contraintes d'unicité
ALTER TABLE G_GEO.TA_GEOTECH_LIBELLE_LONG
ADD CONSTRAINT TA_GEOTECH_LIBELLE_LONG_LIBELLE_UN
UNIQUE("VALEUR")
USING INDEX TABLESPACE G_ADT_INDX;

-- 4. Les droits de lecture, écriture, suppression
GRANT SELECT ON G_GEO.TA_GEOTECH_LIBELLE_LONG TO G_ADMIN_SIG;

/

