/*
TA_GEOTECH_FAMILLE_LIBELLE : Création de la table TA_GEOTECH_FAMILLE_LIBELLE contenant les identifiant des tables TA_GEOTECH_LIBELLE et TA_GEOTECH_FAMILLE, permettant de joindre chaque libellé à sa famille de libellés.
*/

-- 1. La table
CREATE TABLE G_GEO.TA_GEOTECH_FAMILLE_LIBELLE (
	"FID_FAMILLE" NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"FID_LIBELLE" NUMBER(38,0)
 );

-- 2. Les commentaires
COMMENT ON TABLE G_GEO.TA_GEOTECH_FAMILLE_LIBELLE IS 'Table contenant les identifiant des tables TA_GEOTECH_FAMILLE_LIBELLE et TA_GEOTECH_FAMILLE, permettant de joindre chaque libellé à sa famille de libellés.';
COMMENT ON COLUMN G_GEO.TA_GEOTECH_FAMILLE_LIBELLE.FID_FAMILLE IS 'Clé étrangère vers la table TA_GEOTECH_FAMILLE permettant d''associer une famille à un ou plusieurs libellés.';
COMMENT ON COLUMN G_GEO.TA_GEOTECH_FAMILLE_LIBELLE.FID_LIBELLE IS 'Clé étrangère vers la table TA_GEOTECH_LIBELLE permettant d''associer un libellé à une ou plusieurs familles.';

-- 3. Les contraintes
-- Contrainte de clé primaire
ALTER TABLE G_GEO.TA_GEOTECH_FAMILLE_LIBELLE
ADD CONSTRAINT TA_GEOTECH_FAMILLE_LIBELLE_PK
PRIMARY KEY("FID_FAMILLE", "FID_LIBELLE")
USING INDEX TABLESPACE G_ADT_INDX;

-- 5. Les droits de lecture, écriture, suppression
GRANT SELECT ON G_GEO.TA_GEOTECH_FAMILLE_LIBELLE TO G_ADMIN_SIG;

/

