/*
TA_GEOTECH_FAMILLE_LIBELLE_LONG : Création de la table TA_GEOTECH_FAMILLE_LIBELLE_LONG contenant les identifiant des tables TA_GEOTECH_FAMILLE_LIBELLE_LONG et TA_GEOTECH_FAMILLE, permettant de joindre chaque libellé long à sa famille de libellés.
*/

-- 1. La table
CREATE TABLE G_GEO.TA_GEOTECH_FAMILLE_LIBELLE_LONG (
	"FID_FAMILLE" NUMBER(38,0) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"FID_LIBELLE_LONG" NUMBER(38,0)
 );

-- 2. Les commentaires
 COMMENT ON TABLE G_GEO.TA_GEOTECH_FAMILLE_LIBELLE_LONG IS 'Table contenant les identifiant des tables TA_GEOTECH_FAMILLE_LIBELLE_LONG et TA_GEOTECH_FAMILLE, permettant de joindre chaque libellé long à sa famille de libellés.';
COMMENT ON COLUMN G_GEO.TA_GEOTECH_FAMILLE_LIBELLE_LONG.FID_FAMILLE IS 'Clé étrangère vers la table TA_GEOTECH_FAMILLE permettant d''associer une famille à un ou plusieurs libellés longs.';
COMMENT ON COLUMN G_GEO.TA_GEOTECH_FAMILLE_LIBELLE_LONG.FID_LIBELLE_LONG IS 'Clé étrangère vers la table TA_GEOTECH_LIBELLE_LONG permettant d''associer un libellé à une ou plusieurs familles.';

-- 3. Les contraintes
-- Contrainte de clé primaire
ALTER TABLE G_GEO.TA_GEOTECH_FAMILLE_LIBELLE_LONG
ADD CONSTRAINT TA_GEOTECH_FAMILLE_LIBELLE_LONG_PK
PRIMARY KEY("FID_FAMILLE", "FID_LIBELLE_LONG")
USING INDEX TABLESPACE G_ADT_INDX;

-- 5. Les droits de lecture, écriture, suppression
GRANT SELECT ON G_GEO.TA_GEOTECH_FAMILLE_LIBELLE_LONG TO G_ADMIN_SIG;

/

