/*
SEQ_TA_GEOTECH_LIBELLE_COURT_OBJECTID : création de la séquence d'auto-incrémentation de la clé primaire de la table TA_GEOTECH_LIBELLE_COURT
*/

CREATE SEQUENCE SEQ_TA_GEOTECH_LIBELLE_COURT_OBJECTID START WITH 1 INCREMENT BY 1;

/

