/*
SEQ_TA_GEOTECH_LIBELLE_LONG_OBJECTID : création de la séquence d'auto-incrémentation de la clé primaire de la table TA_GEOTECH_LIBELLE_LONG
*/

CREATE SEQUENCE SEQ_TA_GEOTECH_LIBELLE_LONG_OBJECTID START WITH 1 INCREMENT BY 1;

/

